<?php

/**
 * @file
 * Photswipe integration with Drupal module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * The minimum PhotoSwipe version we support.
 */
const PHOTOSWIPE_MIN_PLUGIN_VERSION = '4.0.0';

/**
 * Implements hook_theme().
 */
function photoswipe_theme() {
  return array(
    'photoswipe_image_formatter' => array(
      'variables' => array(
        'item' => NULL,
        'display_settings' => array(),
      ),
      'file' => 'photoswipe.theme.inc',
    ),
    'photoswipe_container' => array(
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_help().
 */
function photoswipe_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the photoswipe module
    case 'help.page.photoswipe':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('<a href=":url">Photoswipe</a> provides a nice javascript-based display for photo galleries, very sleek on mobile browsers.', array(
        ':url' => 'http://www.photoswipe.com/')) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_page_attachments().
 */
function photoswipe_page_attachments(array &$attachments) {
  // Conditionally load on an admin page
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();

  if (\Drupal::config('photoswipe.settings')->get('photoswipe_always_load_non_admin') && $is_admin) {
    \Drupal::service('photoswipe.assets_manager')->attach($attachments);
  }
}
