<?php

/**
 * @file
 * Contains fatsecret.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fatsecret_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fatsecret module.
    case 'help.page.fatsecret':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('allow creation of content based on fatsecret api') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function fatsecret_theme() {
  return [
    'fatsecret' => [
      'render element' => 'children',
    ],
  ];
}


/**
 * Implements hook_page_attachments().
 */
function fatsecret_page_attachments(array &$page){
  $page['#attached']['library'][] = 'fatsecret/fatsecret';
}
