photoswipe.settings:
  type: mapping
  label: Settings
  mapping:
    photoswipe_always_load_non_admin:
      type: boolean
    options:
#      index: integer
      showAnimationDuration:
        type: integer
        label: 'Show Animation Duration'
      hideAnimationDuration:
        type: integer
        label: 'Hide Animation Duration'
      showHideOpacity:
        type: boolean
        label: 'Show Hide Opacity'
      bgOpacity:
        type: float
        label: 'Background Opacity'
      spacing:
        type: float
        label: 'Spacing'
      allowPanToNext:
        type: boolean
        label: 'Allow Pan to Next'
      maxSpreadZoom:
        type: integer
        label: 'Max Spread Zoom'
      loop:
        type: boolean
        label: 'Loop'
      pinchToClose:
        type: boolean
        label: 'Pinch to Close'
      closeOnScroll:
        type: boolean
        label: 'Close on Scroll'
      closeOnVerticalDrag:
        type: boolean
        label: 'Close on Vertical Drag'
      mouseUsed:
        type: boolean
        label: 'Mouse Used'
      escKey:
        type: boolean
        label: 'Escape Key'
      arrowKeys:
        type: boolean
        label: 'Arrow Keys'
      history:
        type: boolean
        label: 'History'
#      galleryUID: Integer
#      galleryPIDs: Boolean
      errorMsg:
        type: string
        label: 'Error Message'
      preload:
        type: array
        label: 'Preload'
      mainClass:
        type: string
        label: 'Main Class'
      focus:
        type: boolean
        label: 'Focus'
      modal:
        type: boolean
        label: 'Modal'
