# Configuration Split Setting menu items definition
entity.config_split.collection:
  title: 'Configuration Split Settings'
  route_name: entity.config_split.collection
  description: 'List Configuration Split settings'
  parent: system.admin_config_development
  weight: 99
